// navbar
export { ReactComponent as HamburgerSVG } from "./navbar/01_hamburger.svg"
export { ReactComponent as PTSLogoFullSVG } from "./navbar/pts_logo_full.svg"
export { ReactComponent as PTSLogoSVG } from "./navbar/pts_logo_mark.svg"
export { ReactComponent as SIMLogoFullSVG } from "./navbar/sim_logo_full.svg"
export { ReactComponent as SIMLogoSVG } from "./navbar/sim_logo_icon.svg"
// sidebar pts
export { ReactComponent as DashboardSVG } from "./sidebar/pts/01_dashboard.svg"
export { ReactComponent as PersonnelStatsSVG } from "./sidebar/pts/02_personnelstats.svg"
export { ReactComponent as PersonnelMgmtSVG } from "./sidebar/pts/03_personnelmgmt.svg"
export { ReactComponent as ProjectMgmtSVG } from "./sidebar/pts/04_projectmgmt.svg"
export { ReactComponent as SonicboltLogoSVG } from "./sidebar/05_sblogo.svg"
// sidebar sim
export { ReactComponent as SIMAdminSVG } from "./sidebar/sim/sim_admin.svg"
export { ReactComponent as AlarmsSVG } from "./sidebar/sim/sim_alarms.svg"
export { ReactComponent as BIMSVG } from "./sidebar/sim/sim_bim.svg"
export { ReactComponent as BuildingStatsSVG } from "./sidebar/sim/sim_buildingstats.svg"
export { ReactComponent as SIMConfigSVG } from "./sidebar/sim/sim_config.svg"
export { ReactComponent as SIMDashboardSVG } from "./sidebar/sim/sim_dashboard.svg"
export { ReactComponent as DeviceMgmtSVG } from "./sidebar/sim/sim_devicemgmt.svg"
export { ReactComponent as EventsSVG } from "./sidebar/sim/sim_events.svg"
export { ReactComponent as ReportsSVG } from "./sidebar/sim/sim_reports.svg"
export { ReactComponent as ScheduleSVG } from "./sidebar/sim/sim_schedule.svg"
export { ReactComponent as SpaceMgmtSVG } from "./sidebar/sim/sim_spacemgmt.svg"
export { ReactComponent as WorkflowSVG } from "./sidebar/sim/sim_workflow.svg"
export { ReactComponent as WorkMgmtSVG } from "./sidebar/sim/sim_workmgmt.svg"
